puts "The students of Villans Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Rached"
puts "Micheal Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of The West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Jeoffrey Baratheon"
puts "Norman Bates"
